config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'comments/new'
  get 'comments/create'
  devise_for :users
  root to: "places#index"
  resources :places, only: [:index, :show] do
    resources :comments, only: [:index, :new, :create]
    resources :user_places, only: [:create]
  end
  resources :comments, only: [:update]
  resources :favourite_places, only: [:index, :create, :destroy]
  resources :trips, only: [:index, :show] do
    resources :user_trips, only: [:create]
  end
  resources :user_trips, only: [:index, :show]
  get "search/trip", to: "trips#search_trip", as: :search_trip
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :place_categories, dependent: :destroy
  has_many :places, through: :place_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/favourite_place.rb
class FavouritePlace < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/favourite_trip.rb
class FavouriteTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :place_categories, dependent: :destroy
  has_many :categories, through: :place_categories
  has_many :comments, dependent: :destroy
  has_many :favourite_places, dependent: :destroy
  has_many :trip_places, dependent: :destroy
  has_many :trips, through: :trip_places
  has_many :user_places, dependent: :destroy
  has_many :users, through: :user_places

  #has_one_attached :audio
end

app/models/place_category.rb
class PlaceCategory < ApplicationRecord
  belongs_to :place
  belongs_to :category
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :favourite_trips, dependent: :destroy
  has_many :trip_places, dependent: :destroy
  has_many :places, through: :trip_places
  has_many :user_trips, dependent: :destroy
  has_many :users, through: :user_trips
end

app/models/trip_place.rb
class TripPlace < ApplicationRecord
  belongs_to :place
  belongs_to :trip
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favourite_places, dependent: :destroy
  has_many :favourite_trips, dependent: :destroy
  has_many :user_trips, dependent: :destroy
  has_many :trips, through: :user_trips
  has_many :user_places, dependent: :destroy
  has_many :places, through: :user_places
  has_many :favourites, through: :favourite_places, source: :place
end

app/models/user_place.rb
class UserPlace < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/user_trip.rb
class UserTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_place, only: :create

  def update
    @comment = Comment.find(params[:id])
    @comment.update(rating_params)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.place = @place
    @comment.user = current_user
    @comment.rating = 0


    respond_to do |format|
      if @comment.save
        format.json
      end
    end
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def rating_params
    params.require(:comment).permit(:rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
  
  def new
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @places = Place.all
    @markers = @places.map do |place|
      {
        lat: place.geo_lat,
        lng: place.geo_long
      }
    end
  end

  def show
    @place = Place.find(params[:id])
    @comments = Comment.where(place_id: params[:id]).order(rating: :desc)
    @users = User.all
    @comment = Comment.new
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def search_trip
    @categories = Category.all
  end

  def index
    if params[:query].present?
      @queries = params[:query].split(";")
      @searched_trips = Trip.where(category: @queries)
    else
      @searched_trips = Trip.all
    end
  end


  def show
    @trip = Trip.find(params[:id])
    places_of_trip = @trip.places.order(:poi_id)
    @markers = places_of_trip.map do |place|
      {
        visited: visited?(place),
        lat: place.geo_lat,
        lng: place.geo_long,
        info_window_html: render_to_string(
          partial: "info_window",
          locals: {
            place: place,
            comment: Comment.new,
            comments: place.comments.order(rating: :desc),
            users: User.all,
            trip: @trip
          }
        )
      }
    end
  end

  private

  def visited?(place)
    current_user.places.include?(place)
    # !place.user_places.where(user_id: current_user).empty?
  end
end

app/controllers/user_trips_controller.rb
class UserTripsController < ApplicationController

  def create
    @user_trip = UserTrip.new
    @user_trip.user = current_user
    @user_trip.trip = Trip.find(params[:trip_id])
    if @user_trip.save
      redirect_to user_trip_path(@user_trip)
    end
  end

  def show
    @user_trip = UserTrip.find(params[:id])
    @user_places = @user_trip.trip.places.select { |place| visited?(place) }
    @favourite_places = FavouritePlace.all
  end

  private

  def visited?(place)
    !place.user_places.where(user_id: current_user).empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attachment_safe_url(attachment)
    return attachment if attachment.class == String
    return image_path 'default.jpg' if attachment.nil?
    # return image_path 'default.jpg' unless attachment.blob.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wanders - Partez à la découverte de ce qui vous entoure</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="ScreenOrientation" content="autoRotate:disabled">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#444285">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  </head>

  <body>

    <div class="site-container">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <div class="site-content">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.actu.fr/uploads/2021/03/adobestock-264549883.jpeg);">
  <div class="container">
    <h1>Wanders</h1>
    <p>Balades architecturales à Paris</p>
    <%= link_to "Inscrivez-vous maintenant !", new_user_registration_path %>
  </div>
</div>

app/views/shared/_avatar.html.erb
<%= image_tag attachment_safe_url(pic), class: "avatar-bordered", alt: "avatar-bordered" %>

app/views/shared/_comments.html.erb
<div class="comment-card">
 <div class="ctn-left">
  <div class="user-avatar">
    <%= link_to user_path(comment.user) do %>
      <%= render "shared/avatar", pic: comment.user.profile_pic, class: "avatar-bordered-comment" %>
    <% end %>
  </div>
  <div class="comment-rating" data-controller='ratings'
       data-ratings-id-value="<%= comment.id %>">
    <span href="#"
       data-ratings-target = 'upvote'
       data-action = 'click->ratings#vote'
       data-description = 'upvote'>
      <i class="fa-solid fa-thumbs-up"
         data-value = 'upvote'></i>
    </span>
    <h4 data-ratings-target = 'rating'><%= comment.rating %></h4>
    <span href="#"
       data-ratings-target = 'downvote'
       data-action = 'click->ratings#vote'
       data-description = 'downvote'>
      <i class="fa-solid fa-thumbs-down"
         data-value = 'downvote'></i>
    </span>
  </div>
 </div>
 <div class="user-comment">
  <h3 class="user-name"><%= comment.user.username %></h3>
  <p class="user-content"><%= comment.content %></p>
 </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="d-flex justify-content-evenly w-footer-rectangle">
    <%= link_to places_path, class: "d-flex flex-column align-items-center justify-content-between" do %>
      <i class="fa-solid fa-archway"></i>
      <span>Accueil</span>
    <% end %>

    <%= link_to search_trip_path, class: "d-flex flex-column align-items-center justify-content-between" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
      <span>Recherche</span>
    <% end %>

    <%= link_to favourite_places_path, class: "d-flex flex-column align-items-center justify-content-between" do %>
      <i class="fa-solid fa-book"></i>
      <span>Favoris</span>
    <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= image_tag 'Wanders_v2.png', class: "nav-logo" %>
    <% if user_signed_in? %>
      <%= image_tag attachment_safe_url(current_user.profile_pic), class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Mon profil", "#", class: "dropdown-item" %>
        <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    <% else %>
      <div style="display: inherit">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
        <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_user_infos.html.erb
<div class="container user-infos-container">
  <div class="container user-infos d-flex">
    <div class="container-left">
      <%= render "shared/avatar", pic: @user.profile_pic, class: "avatar-bordered-comment" %>
    </div>
    <div class="container-right">
      <h4><%= @user.username %></h4>
      <p>Inscrit depuis le <%= @user.created_at%></p>
    </div>
  </div>
  <div class="user-favorites">
    <div class="section-title">
      <h4>Favoris</h4>
      <i class="fa-solid fa-plus"></i>
    </div>
    <div class="section">
    <%= @user.favourite_places.each do |fav| %>
      <div class="place-mini">
        <div class="place-mini-img">
          <%= image_tag fav.url_image, alt: "place image" %>
        </div>
        <div class="place-mini-info">
          <h3><%= fav.name %></h3>
          <p><%= fav.address %></p>
        </div>
    <% end %>
    </div>
  </div>
</div>