config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'comments/new'
  get 'comments/create'
  devise_for :users
  root to: "places#index"
  resources :places, only: [:index, :show] do
    resources :comments, only: [:index, :new, :create]
    resources :user_places, only: [:create]
  end
  resources :comments, only: [:update]
  resources :favourite_places, only: [:index, :create, :destroy]
  resources :trips, only: [:index, :show] do
    resources :user_trips, only: [:create]
  end
  resources :user_trips, only: [:index, :show]
  get "search/trip", to: "trips#search_trip", as: :search_trip
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :place_categories, dependent: :destroy
  has_many :places, through: :place_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/favourite_place.rb
class FavouritePlace < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/favourite_trip.rb
class FavouriteTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :place_categories, dependent: :destroy
  has_many :categories, through: :place_categories
  has_many :comments, dependent: :destroy
  has_many :favourite_places, dependent: :destroy
  has_many :trip_places, dependent: :destroy
  has_many :trips, through: :trip_places
  has_many :user_places, dependent: :destroy
  has_many :users, through: :user_places

  #has_one_attached :audio
end

app/models/place_category.rb
class PlaceCategory < ApplicationRecord
  belongs_to :place
  belongs_to :category
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :favourite_trips, dependent: :destroy
  has_many :trip_places, dependent: :destroy
  has_many :places, through: :trip_places
  has_many :user_trips, dependent: :destroy
  has_many :users, through: :user_trips
end

app/models/trip_place.rb
class TripPlace < ApplicationRecord
  belongs_to :place
  belongs_to :trip
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :favourite_places, dependent: :destroy
  has_many :favourite_trips, dependent: :destroy
  has_many :user_trips, dependent: :destroy
  has_many :trips, through: :user_trips
  has_many :user_places, dependent: :destroy
  has_many :places, through: :user_places
  has_many :favourites, through: :favourite_places, source: :place
end

app/models/user_place.rb
class UserPlace < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/user_trip.rb
class UserTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_place, only: :create

  def update
    @comment = Comment.find(params[:id])
    @comment.update(rating_params)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.place = @place
    @comment.user = current_user
    @comment.rating = 0


    respond_to do |format|
      if @comment.save
        format.json
      end
    end
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def rating_params
    params.require(:comment).permit(:rating)
  end
end

app/controllers/favourite_places_controller.rb
class FavouritePlacesController < ApplicationController
  def index
    @favourite_places = FavouritePlace.all
  end

  def create
    @favourite = FavouritePlace.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.json { render json: { success: @favourite.save } }
      end
    end
  end

  def destroy
    @favourite = FavouritePlace.find_by(favourite_params)
    respond_to do |format|
      if @favourite.destroy
        format.json { render json: { success: @favourite.destroy } }
      end
    end

  end

  private

  def favourite_params
    params.require(:favourite_place).permit(:user_id, :place_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
  
  def new
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]
  def index
    @places = Place.all
    @markers = @places.map do |place|
      {
        lat: place.geo_lat,
        lng: place.geo_long
      }
    end
  end

  def show
    @place = Place.find(params[:id])
    @comments = Comment.where(place_id: params[:id]).order(rating: :desc)
    @users = User.all
    @comment = Comment.new
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def search_trip
    @categories = Category.all
  end

  def index
    if params[:query].present?
      @queries = params[:query].split(";")
      @searched_trips = Trip.where(category: @queries)
    else
      @searched_trips = Trip.all
    end
  end


  def show
    @trip = Trip.find(params[:id])
    places_of_trip = @trip.places.order(:poi_id)
    @markers = places_of_trip.map do |place|
      {
        visited: visited?(place),
        lat: place.geo_lat,
        lng: place.geo_long,
        info_window_html: render_to_string(
          partial: "info_window",
          locals: {
            place: place,
            comment: Comment.new,
            comments: place.comments.order(rating: :desc),
            users: User.all,
            trip: @trip
          }
        )
      }
    end
  end

  private

  def visited?(place)
    current_user.places.include?(place)
    # !place.user_places.where(user_id: current_user).empty?
  end
end

app/controllers/user_places_controller.rb
class UserPlacesController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @trip = Trip.find(params[:trip_id])
    @user_places = UserPlace.new
    @user_places.user = current_user
    @user_places.place = @place
    trip_places = @trip.places.order(:poi_id)

    respond_to do |format|
      if @user_places.save
        format.json {
          render json: {
            marker: place_marker(@place, @trip),
            first: trip_places.first == @place,
            last: trip_places.last == @place
          }
        }
      else
        format.json { render json: {} }
      end
    end
  end

  private

  def place_marker(place, trip)
    {
      visited: true,
      lat: place.geo_lat,
      lng: place.geo_long,
      info_window_html: render_to_string(
        partial: "trips/info_window", locals: {
          place: place,
          comment: Comment.new,
          comments: place.comments.order(rating: :desc),
          users: User.all,
          trip: trip
        },
        formats: :html
      )
    }
  end
end

app/controllers/user_trips_controller.rb
class UserTripsController < ApplicationController

  def create
    @user_trip = UserTrip.new
    @user_trip.user = current_user
    @user_trip.trip = Trip.find(params[:trip_id])
    if @user_trip.save
      redirect_to user_trip_path(@user_trip)
    end
  end

  def show
    @user_trip = UserTrip.find(params[:id])
    @user_places = @user_trip.trip.places.select { |place| visited?(place) }
    @favourite_places = FavouritePlace.all
  end

  private

  def visited?(place)
    !place.user_places.where(user_id: current_user).empty?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def attachment_safe_url(attachment)
    return attachment if attachment.class == String
    return image_path 'default.jpg' if attachment.nil?
    # return image_path 'default.jpg' unless attachment.blob.present?
  end
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/favourite_places/index.html.erb
<div class="fav-place-container">
  <h1>Lieux favoris</h1>
  <div data-controller="display-fav-description">

    <% @favourite_places.each do |favourite_place| %>

      <div class= "fav-place-details-container" data-action="click->display-fav-description#revealContent">

        <div class="fav-place-card">
        <div class="image">
          <%= image_tag favourite_place.place.url_image, alt: "place's image" %>
          </div>
          <div class="fav-place-info" >
            <h2><%= favourite_place.place.name %></h2>
            <div class="trip-icon">
              <p class="favori-icon"><i class="fa-solid fa-star"></i></p>
            </div>
          </div>
        </div>

        <div class="place-description" data-display-fav-description-target="description">
          <p><%= favourite_place.place.description %></p>
        </div>

      </div>

    <% end %>

  </div>
</div>

app/views/places/index.html.erb
<div class="map"
  data-controller="map"
  data-map-home-value="true"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<div class="d-flex justify-content-around button-content">
  <%= link_to("Me balader", search_trip_path, class: "btn-balade") %>
  <%= link_to("Aller à cette adresse", places_path, class: "btn-adresse") %>
</div>

app/views/places/show.html.erb
<div class="card-place">
  <%= image_tag @place.url_image, alt: "place's image" %>
  <div>
    <div>
      <h2><%= @place.name %></h2>
      <p><%= @place.address %></p>
      <p>Note : <%= @place.average_rating %></p>


    </div>
    <div>

      <%= @place.description %>
    </div>
  </div>

app/views/trips/_info_window.html.erb
<div class="card-place" data-controller='comment-section user-place'>
  <% if place.url_image %>
    <%= image_tag place.url_image, alt: "place's image" %>
  <% end %>
  <div class=card-info>
    <div class="place-data">
      <h2><%= place.name %></h2>
      <p class="address" style="font-style: italic;"><%= place.address %></p>
      <p>
        <% rating = place.average_rating.to_i %>
        <% missing_star = 5 - rating %>
        <% rating.times do  %>
          <span class="fa-solid fa-star" style="color: #3698B1"></span>
        <% end %>
        <% missing_star.times do  %>
          <span class="fa-regular fa-star" style="color: #3698B1"></span>
        <% end %>
      </p>
      <div class="visited-area">
        <% if place.users.include?(current_user) %>
          <p><i class="fa-solid fa-circle-check"></i></p>
        <% else %>
          <p>Marquer comme visité<p>
          <%= button_to place_user_places_path(place),
                        data: {
                          turbo_method: :post ,
                          action: "click->user-place#create",
                          trip_id: @trip.id
                        },
                        class: "transparent-button" do %>
            <div class="form-check form-switch">
              <%# <p>Marquer comme visité<p> %>
              <%# <label class="form-check-label" for="flexSwitchCheckDefault" id="visited-label"></label> %>
              <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="card-description">
      <%= place.description %>
    </div>
    <div class="player-audio">
      <% if place.audio_file %>
        <%= audio_tag place.audio_file, controls: true %>
      <% end %>
    </div>
  </div>
  <h5>Enrichissez ce lieu :</h5>
   <i class="fa-solid fa-plus comment-cta"
     data-comment-section-target='button'
     data-action = 'click->comment-section#displayComments'>
  </i>
  <div class="container d-none"
       data-comment-section-target='section'>
     <%= simple_form_for [place, comment], html: {data: {comment_section_target: 'form', action: "submit->comment-section#createComment"}} do |f| %>
        <%= f.input :content, label: false%>
        <%= f.submit 'Valider', class: "w-btn-primary" %>
      <% end %>
  <div class="list" data-comment-section-target = 'list'>
    <% comments.each do |c| %>
      <%= render  'shared/comments', comment: c%>
    <% end %>
  </div>
</div>

app/views/trips/index.html.erb
<div class="trip-container">
  <h1 class="text-center mb-5">Nos balades</h1>
    <div data-controller="display-trip-details">
      <% @searched_trips.each do |trip| %>

          <div class="trip-details-container" data-action="click->display-trip-details#revealContent" data-display-trip-details-target="container">

            <div class="trip-header">
              <div>
                <%= image_tag trip.places.first.url_image, alt: "place's image" %>
              </div>
              <div class="trip-title">
                <p class="title"><%= trip.name %></p>
                <div class="description-container">
                  <p class="duration"><i class="fa-solid fa-clock"></i> <br> <%= trip.duration %> mn</p>
                  <p class="start"><i class="fa-solid fa-flag-checkered"></i> <br> <%= trip.places.first.address %></p>
                </div>
              </div>
            </div>

            <div class="card-trip" data-display-trip-details-target="info">
                <div>
                  <p class="key-figures"><%= trip.places.count %> </p>
                </div>
                <div>
                  <p class="key-icon"><i class="fa-solid fa-location-dot"></i></p>
                </div>
                <div class="card-badges">
                  <span class="w-tag-badge-trip"><%= trip.category %></span>
                  <%= link_to("C'est parti !", trip_path(trip), class: "w-btn-trip") %>
                </div>
            </div>

          </div>

      <% end %>
    </div>
</div>

app/views/trips/search_trip.html.erb
<div class="search-container" data-controller="category-selection">

  <h1 class="text-center mt-4 mb-4">Qu'as-tu envie de voir ?</h1>
  <div class="tag-container">
    <div class="tags">
        <% @categories.each do |category| %>
          <div class="w-tag-badge" data-category-selection-target="category" data-action="click->category-selection#selected"><%= category.name %></div>
        <% end %>
    </div>
  </div>

  <%= form_with url: trips_path, method: :get, html: {class:
    "trip-form", data: {category_selection_target: "form"}} do |f| %>
    <%= f.text_field :query,
                     class: "d-none",
                     data: {category_selection_target: "input"} %>

    <%= f.submit "C'est parti !", class: "w-button button-start-trip" %>
    <% end %>
</div>

app/views/trips/show.html.erb
<div class="map"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  data-map-route-value="<%= true %>">
</div>

<%= button_to "Balade terminée", trip_user_trips_path(@trip), data: { turbo_method: :post } , class: "btn-balade-terminee"%>

app/views/user_trips/show.html.erb
<div class="trip-recap">
<h2>Résumé de la balade</h2>
  <div class="distance-recap">
    <div class="d-flex justify-content-around">
      <div class="distance">
        <i class="fa-solid fa-shoe-prints"></i><br>
        <h4><%= @user_trip.trip.kms %> km</h4>
      </div>
      <div class="places-recap">
        <i class="fa-solid fa-location-dot"></i><br>
        <h4><%= "#{@user_places.length}" %></h4>
      </div>
    </div>
  </div>
  <div class="playlist">
    <h4>Tes étapes du jour</h3>
    <% @user_places.each do |place| %>
      <div class="place-mini">
        <div class="place-mini-card">
          <div class="place-mini-img">
            <%= image_tag place.url_image, alt: "place image" %>
          </div>
          <div class="place-mini-info position-relative">
              <% if !current_user.favourites.include?(place) %>
                <div class="text-right position-absolute star-regular">
                  <i class="fa-regular fa-star" data-add-favourite-target="icon" data-place="<%= place.id %>" data-user="<%= current_user.id %>" data-controller="add-favourite" data-action="click->add-favourite#changeIcon"></i>
                </div>
              <% else %>
                <div class="text-right position-absolute star-solid">
                  <% favourite_id = @favourite_places.find_by(user_id: current_user.id, place_id: place.id).id %>
                  <i class="fa-solid fa-star" data-add-favourite-target="icon" data-place="<%= place.id %>" data-user="<%= current_user.id %>"  data-favid="<%= favourite_id.to_s %>" data-controller="add-favourite" data-action="click->add-favourite#changeIcon"></i>
                </div>
              <% end %>
            <h3><%= place.name %></h3>
            <p><%= place.address %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/user_infos" %>